### ISSUE TITLE
Where is the documentation of this package?

### ISSUE THREAD

**Issue by ifaniqbal** [zendframework/ZendSearch#21]
Where is the documentation of this package?

**Comment by weierophinney** [comment]
The package has been deprecated essentially since we ported it, as we were never able to get tests running correctly under 5.3, and it has gone out-of-date with the ZF1 version. Usage is the same as ZF1: http://framework.zend.com/manual/1.12/en/zend.search.lucene.html. Neither library supports recent versions of Lucene (they're pinned to versions that are now 4 or 5 years old), and, as such, you will not have interoperability with any Java application using Lucene currently.

Personally, I would recommend using Solr or ElasticSearch at this time.

**Comment by goldsky** [comment]
If this is deprecated, I think it's better to state it in README.md, so everyone is aware about that at the first sight.
May be with a planned roadmap.

Google always lands people to this repo.
I had never thought about it, if I didn't read this *closed* issue.

Just my 2¢.
